/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Aug 22, 2011, 12:22:01 PM
 */
package ldap.pkgfinal.code;

//import java.security.acl.NotOwnerException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import javax.swing.JFileChooser;
import java.io.*;
import java.lang.String;
import java.net.*;

/**
 *
 * @author Anshul
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(206, 98, 89, 20);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(206, 136, 89, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Enter User Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Enter password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 140, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("OK");
        jButton1.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(63, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 190, 63, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon("N:\\ldap final code-Client Server\\2560_1600_20100813013548645780.jpg")); // NOI18N
        jLabel1.setText("Enter password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        /*String string = "";
        string = String.format(evt.getActionCommand());
        System.out.println(string);
        if (string.equals("a1") || string.equals("b2") || string.equals("c3")) {
            JOptionPane.showMessageDialog(null, "CORRECT");
        } else {
            JOptionPane.showMessageDialog(null, "INCORRECT");
        }
        /*else
        JOptionPane.showMessageDialog(null, "incorrect");
         */

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int retval,flag = 0;
        String q = "";
        String p = "";
        boolean b;
        q = jTextField1.getText();
        p = jPasswordField1.getText();
         try
        {
             Socket ss = new Socket("ANURAG-PC",1056);
             BufferedReader br=new BufferedReader(new InputStreamReader(ss.getInputStream()));
             
             //String st;
             //st=br.readLine();
             System.out.println(br.readLine());
              PrintWriter pw= new PrintWriter(ss.getOutputStream(),true);
             String str="hifggv";
             pw.println(q);
             pw.println(p);
            // pw.println(p);
  
             //String st;
             //st=br.readLine();
             //System.out.println(br.readLine());
             String s=br.readLine();
             flag=Integer.parseInt(s);
             System.out.println(flag);
             
        
             
        
        
      /*  Fileuser use1 = new Fileuser();
        try {
            flag=use1.userfile(q,p);
        } 
        catch (IOException ex) {
            //Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
*/        //System.out.println(q);
        if (flag==1){//((q.equals("a1") || q.equals("b2") || q.equals("c3") || q.equals("admin")) && p.equals("password")){
            //Fc:
            retval = jFileChooser1.showOpenDialog(NewJFrame.this);
            if (retval == JFileChooser.APPROVE_OPTION) {
                Filehand qqw = new Filehand();
                int i;

                File fileToOpen = jFileChooser1.getSelectedFile();
                String a = jFileChooser1.getSelectedFile().getName();
                int ind = a.lastIndexOf('.');
                a = a.substring(0, ind);
                //System.out.println("Filename without Extension: " + a + " " + q);
                
                pw.println(a);
                String temp=br.readLine();
                i=Integer.parseInt(temp);
                
     //          i = qqw.in1(a, q);
                //try {
                    if (i == 1) {
                        Desktop.getDesktop().open(fileToOpen);
                    } else {
                        JOptionPane.showMessageDialog(null, "Access Denied");
            //retval = jFileChooser1.showOpenDialog(NewJFrame.this);
              //goto Fc;
              }
                    }
        
                //}
               
                
            }
            // b=addOwner(principal NewJFrame,principal this) throws NotOwnerException;
            //JOptionPane.showMessageDialog(null,"CORRECT");
         
else {
            JOptionPane.showMessageDialog(null, "INCORRECT USERID OR PASSWORD");
        }


        }
        catch (Exception exception) {
                    System.out.println("Problem occour when to open the file");
                } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    void filewrite() {
        Filehand f1 = new Filehand("admin", new String[]{"file1", "file2", "file3", "file4", "file5"});
        Filehand f2 = new Filehand("user1", new String[]{"file1", "file2", "file3", "file5"});
        Filehand f3 = new Filehand("user2", new String[]{"file1", "file4", "file5"});
        Filehand f4 = new Filehand("user3", new String[]{"file1", "file5"});
        
        try {
            FileOutputStream fs = new FileOutputStream("abc.txt");
            ObjectOutputStream os = new ObjectOutputStream(fs);
            os.writeObject(f1);
            os.writeObject(f2);
            os.writeObject(f3);
            os.writeObject(f4);
            os.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
void userwrite()
{
        Fileuser u1=new Fileuser("admin","password");
        Fileuser u2=new Fileuser("user1","pass1");
        Fileuser u3=new Fileuser("user2","pass2");
        Fileuser u4=new Fileuser("user3","pass3");
     
            try {
            FileOutputStream fu= new FileOutputStream("userfile.txt");
            ObjectOutputStream ou1=new ObjectOutputStream(fu);
            ou1.writeObject(u1);
            ou1.writeObject(u2);
            ou1.writeObject(u3);
            ou1.writeObject(u4);
            ou1.close();
                    // TODO code application logic here
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
}
    public static void main(String args[]) {
//        Fileuser userpass;
  //      userpass
        
        NewJFrame grp = new NewJFrame();
        grp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        grp.setSize(350, 200);
        grp.userwrite();
        grp.filewrite();
        
        //bucky.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
